config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("lims.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("labdata/", include("lims.labdata.urls")),
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

lims/labdata/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.homepage, name="labdata_homepage"),
    path(
        "delete/<str:model_name>/<int:item_id>/",
        views.confirm_delete_view,
        name="confirm_delete",
    ),
    path("organism/", views.organism_form_view, name="create_organism"),
    path(
        "organism/detail/<int:pk>/",
        views.organism_detail_view,
        name="detail_organism",
    ),
    path("organism/<int:pk>/", views.organism_form_view, name="update_organism"),
    path("specimen/", views.specimen_form_view, name="create_specimen"),
    path(
        "specimen/detail/<int:pk>/",
        views.specimen_detail_view,
        name="detail_specimen",
    ),
    path("specimen/<int:pk>/", views.specimen_form_view, name="update_specimen"),
    path("sampletype/", views.sampletype_form_view, name="create_sampletype"),
    path(
        "sampletype/detail/<int:pk>/",
        views.sampletype_detail_view,
        name="detail_sampletype",
    ),
    path(
        "sampletype/<int:pk>/",
        views.sampletype_form_view,
        name="update_sampletype",
    ),
    path("sample/", views.sample_form_view, name="create_sample"),
    path(
        "sample/detail/<int:pk>/",
        views.sample_detail_view,
        name="detail_sample",
    ),
    path("sample/<int:pk>/", views.sample_form_view, name="update_sample"),
    path("test/", views.test_form_view, name="create_test"),
    path("test/detail/<int:pk>/", views.test_detail_view, name="detail_test"),
    path("test/<int:pk>/", views.test_form_view, name="update_test"),
    path("inventory/", views.inventory_form_view, name="create_inventory"),
    path(
        "inventory/detail/<int:pk>/",
        views.inventory_detail_view,
        name="detail_inventory",
    ),
    path("inventory/<int:pk>/", views.inventory_form_view, name="update_inventory"),
    path(
        "sample_results/",
        views.sample_results_form_view,
        name="create_sample_results",
    ),
    path(
        "sample_results/detail/<int:pk>/",
        views.sample_results_detail_view,
        name="detail_sample_results",
    ),
    path(
        "sample_results/<int:pk>/",
        views.sample_results_form_view,
        name="update_sample_results",
    ),
]

lims/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

lims/labdata/models.py
from django.db import models
from django.urls import reverse

from lims.users.models import Analyst


class Organism(models.Model):
    sci_name = models.CharField(max_length=200, unique=True)
    common_name = models.CharField(max_length=200)

    def __str__(self):
        return self.common_name

    def get_absolute_url(self):
        return reverse("detail_organism", args=[str(self.id)])


class Specimen(models.Model):
    GENDER_CHOICES = [
        ("M", "Male"),
        ("F", "Female"),
    ]

    RACE_CHOICES = [
        ("W", "White"),
        ("B", "Black or African American"),
        ("A", "Asian"),
        ("H", "Hispanic or Latino"),
        ("N", "American Indian or Alaska Native"),
        ("O", "Native Hawaiian or Other Pacific Islander"),
        ("U", "Unknown or Not Reported"),
    ]

    organism = models.ForeignKey(Organism, on_delete=models.CASCADE)
    specimen_id = models.CharField(max_length=255, unique=True)
    first_name = models.CharField(max_length=100, blank=True, default="")
    last_name = models.CharField(max_length=100, blank=True, default="")
    dob = models.DateField(blank=True, null=True)
    cohort = models.CharField(max_length=100, blank=True, default="")
    gender = models.CharField(
        max_length=1,
        choices=GENDER_CHOICES,
        blank=True,
        default="",
    )
    race = models.CharField(max_length=1, choices=RACE_CHOICES, blank=True, default="")

    def __str__(self):
        return f"{self.specimen_id}"

    def get_absolute_url(self):
        return reverse("detail_specimen", args=[str(self.id)])


class SampleType(models.Model):
    source = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.source

    def get_absolute_url(self):
        return reverse("detail_sampletype", args=[str(self.id)])


class Sample(models.Model):
    collect_date = models.DateField()
    type = models.ForeignKey(SampleType, on_delete=models.SET_NULL, null=True)
    specimen = models.ForeignKey(Specimen, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.specimen} {self.type}"

    def get_absolute_url(self):
        return reverse("detail_sample", args=[str(self.id)])


class Test(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    reportable_results = models.TextField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("detail_test", args=[str(self.id)])


class Inventory(models.Model):
    name = models.CharField(max_length=200)
    cat_num = models.CharField(max_length=200)
    lot_num = models.CharField(max_length=200)
    exp = models.DateField()
    in_use = models.BooleanField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("detail_inventory", args=[str(self.id)])


class SampleResults(models.Model):
    sample = models.ForeignKey(Sample, on_delete=models.CASCADE)
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    analyst = models.ForeignKey(Analyst, on_delete=models.SET_NULL, null=True)
    reagents = models.ManyToManyField("Inventory", related_name="sample_results")
    date = models.DateField()
    results = models.TextField()

    def __str__(self):
        return f"{self.sample} {self.test} Results"

    def get_absolute_url(self):
        return reverse("detail_sample_results", args=[str(self.id)])

lims/labdata/forms.py
from django import forms

from . import models


class OrganismForm(forms.ModelForm):
    class Meta:
        model = models.Organism
        fields = "__all__"  # noqa: DJ007


class SpecimenForm(forms.ModelForm):
    class Meta:
        model = models.Specimen
        fields = [
            "organism",
            "specimen_id",
            "first_name",
            "last_name",
            "dob",
            "cohort",
            "gender",
            "race",
        ]
        widgets = {
            "dob": forms.DateInput(attrs={"type": "date"}),
        }


class SampleForm(forms.ModelForm):
    class Meta:
        model = models.Sample
        fields = "__all__"  # noqa: DJ007
        widgets = {
            "collect_date": forms.DateInput(attrs={"type": "date"}),
        }


class SampleTypeForm(forms.ModelForm):
    class Meta:
        model = models.SampleType
        fields = "__all__"  # noqa: DJ007


class TestForm(forms.ModelForm):
    class Meta:
        model = models.Test
        fields = "__all__"  # noqa: DJ007


class InventoryForm(forms.ModelForm):
    class Meta:
        model = models.Inventory
        fields = "__all__"  # noqa: DJ007
        widgets = {
            "exp": forms.DateInput(attrs={"type": "date"}),
        }


class SampleResultsForm(forms.ModelForm):
    class Meta:
        model = models.SampleResults
        fields = "__all__"  # noqa: DJ007
        widgets = {
            "date": forms.DateInput(attrs={"type": "date"}),
        }

lims/labdata/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse

from . import forms
from . import models


def homepage(request):
    organisms = models.Organism.objects.all()
    specimens = models.Specimen.objects.all()
    samples = models.Sample.objects.all()
    tests = models.Test.objects.all()
    inventory = models.Inventory.objects.all()
    sample_results = models.SampleResults.objects.all()
    return render(
        request,
        "labdata/homepage.html",
        {
            "organisms": organisms,
            "specimens": specimens,
            "samples": samples,
            "tests": tests,
            "inventories": inventory,
            "sample_results": sample_results,
            "tables": [
                "Organism",
                "Specimen",
                "Sample",
                "Test",
                "Inventory",
                "Results",
            ],
        },
    )


def confirm_delete_view(request, model_name, item_id):
    model = {
        "organism": models.Organism,
        "specimen": models.Specimen,
        "sample": models.Sample,
    }.get(
        model_name.lower(),
    )
    if not model:
        msg = "Model not found."
        raise Http404(msg)

    item = get_object_or_404(model, pk=item_id)
    item_details = {
        field.name: getattr(item, field.name)
        for field in item._meta.fields  # noqa: SLF001
    }

    if request.method == "POST":
        item.delete()
        return redirect("labdata_homepage")  # Adjust as needed

    return render(
        request,
        "labdata/confirm_delete.html",
        {
            "item_details": item_details,
            "model_name": model_name,
            "item_id": item_id,
        },
    )


def organism_detail_view(request, pk):
    organism = get_object_or_404(models.Organism, pk=pk)
    return render(request, "labdata/detail_organism.html", {"organism": organism})


def organism_form_view(request, pk=None):
    instance = get_object_or_404(models.Organism, pk=pk) if pk else None
    if request.method == "POST":
        form = forms.OrganismForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect(reverse("labdata_homepage"))  # Adjust as needed
    else:
        form = forms.OrganismForm(instance=instance)
    return render(
        request,
        "labdata/form_template.html",
        {
            "form": form,
            "title": "Edit Organism" if pk else "Create New Organism",
            "button_label": "Update" if pk else "Create",
        },
    )


def specimen_detail_view(request, pk):
    specimen = get_object_or_404(models.Specimen, pk=pk)
    return render(request, "labdata/detail_specimen.html", {"specimen": specimen})


def specimen_form_view(request, pk=None):
    instance = get_object_or_404(models.Specimen, pk=pk) if pk else None
    if request.method == "POST":
        form = forms.SpecimenForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect(reverse("labdata_homepage"))  # Adjust as needed
    else:
        form = forms.SpecimenForm(instance=instance)
    return render(
        request,
        "labdata/form_template.html",
        {
            "form": form,
            "title": "Edit Specimen" if pk else "Create New Specimen",
            "button_label": "Update" if pk else "Create",
        },
    )


def sampletype_detail_view(request, pk):
    sample_type = get_object_or_404(models.SampleType, pk=pk)
    return render(
        request,
        "labdata/detail_sample_type.html",
        {"sample_type": sample_type},
    )


def sampletype_form_view(request, pk=None):
    instance = get_object_or_404(models.SampleType, pk=pk) if pk else None
    if request.method == "POST":
        form = forms.SampleTypeForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect(reverse("labdata_homepage"))  # Adjust as needed
    else:
        form = forms.SampleTypeForm(instance=instance)
    return render(
        request,
        "labdata/form_template.html",
        {
            "form": form,
            "title": "Edit Sample Type" if pk else "Create New Sample Type",
            "button_label": "Update" if pk else "Create",
        },
    )


def sample_detail_view(request, pk):
    sample = get_object_or_404(models.Sample, pk=pk)
    return render(request, "labdata/detail_sample.html", {"sample": sample})


def sample_form_view(request, pk=None):
    instance = get_object_or_404(models.Sample, pk=pk) if pk else None
    if request.method == "POST":
        form = forms.SampleForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect(reverse("labdata_homepage"))  # Adjust as needed
    else:
        form = forms.SampleForm(instance=instance)
    return render(
        request,
        "labdata/form_template.html",
        {
            "form": form,
            "title": "Edit Sample" if pk else "Create New Sample",
            "button_label": "Update" if pk else "Create",
        },
    )


def test_detail_view(request, pk):
    test = get_object_or_404(models.Test, pk=pk)
    return render(request, "labdata/detail_test.html", {"test": test})


def test_form_view(request, pk=None):
    instance = get_object_or_404(models.Test, pk=pk) if pk else None
    if request.method == "POST":
        form = forms.TestForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect(reverse("labdata_homepage"))  # Adjust as needed
    else:
        form = forms.TestForm(instance=instance)
    return render(
        request,
        "labdata/form_template.html",
        {
            "form": form,
            "title": "Edit Test" if pk else "Create New Test",
            "button_label": "Update" if pk else "Create",
        },
    )


def inventory_detail_view(request, pk):
    inventory_item = get_object_or_404(models.Inventory, pk=pk)
    return render(
        request,
        "labdata/detail_inventory.html",
        {"inventory": inventory_item},
    )


def inventory_form_view(request, pk=None):
    instance = get_object_or_404(models.Inventory, pk=pk) if pk else None
    if request.method == "POST":
        form = forms.InventoryForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect(reverse("labdata_homepage"))  # Adjust as needed
    else:
        form = forms.InventoryForm(instance=instance)
    return render(
        request,
        "labdata/form_template.html",
        {
            "form": form,
            "title": "Edit Inventory Item" if pk else "Create New Inventory Item",
            "button_label": "Update" if pk else "Create",
        },
    )


def sample_results_detail_view(request, pk):
    results = get_object_or_404(models.SampleResults, pk=pk)
    return render(
        request,
        "labdata/detail_sample_results.html",
        {"sample_result": results},
    )


def sample_results_form_view(request, pk=None):
    instance = get_object_or_404(models.SampleResults, pk=pk) if pk else None
    if request.method == "POST":
        form = forms.SampleResultsForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect(reverse("labdata_homepage"))  # Adjust as needed
    else:
        form = forms.SampleResultsForm(instance=instance)
    return render(
        request,
        "labdata/form_template.html",
        {
            "form": form,
            "title": "Edit Sample Results" if pk else "Create New Sample Results",
            "button_label": "Update" if pk else "Create",
        },
    )

lims/templates/labdata/confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <h2>Confirm Delete</h2>
    <p>Are you sure you want to delete the following item?</p>
    <ul>
      {% for field, value in item_details.items %}
        <li>
          <strong>{{ field }}:</strong> {{ value }}
        </li>
      {% endfor %}
    </ul>
    <form action="{% url 'confirm_delete' model_name item_id %}" method="post">
      {% csrf_token %}
      <a href="{% url 'labdata_homepage' %}" class="btn btn-secondary">Cancel</a>
      <button type="submit" class="btn btn-danger">Delete</button>
    </form>
  </div>
{% endblock content %}

lims/templates/labdata/detail_inventory.html
{% extends "base.html" %}

{% load role_tags %}

{% block content %}
  <div class="container mt-4">
    <h1>Inventory Details</h1>
    <dl class="row mt-4">
      <dt class="col-sm-2">Name</dt>
      <dd class="col-sm-10">
        {{ inventory.name }}
      </dd>
      <dt class="col-sm-2">Catalog Number</dt>
      <dd class="col-sm-10">
        {{ inventory.cat_num }}
      </dd>
      <dt class="col-sm-2">Lot Number</dt>
      <dd class="col-sm-10">
        {{ inventory.lot_num }}
      </dd>
      <dt class="col-sm-2">Expiration Date</dt>
      <dd class="col-sm-10">
        {{ inventory.exp }}
      </dd>
      <dt class="col-sm-2">In Use</dt>
      <dd class="col-sm-10">
        {{ inventory.in_use }}
      </dd>
      <!-- Add more fields as needed -->
    </dl>
    <!-- Navigation Buttons -->
    <div class="mt-3">
      <!-- Go back button -->
      <a href="{% url 'labdata_homepage' %}" class="btn btn-secondary">Back to List</a>
      {% if request.user|has_role:"PI" %}
        <!-- Edit button -->
        <a href="{% url 'update_inventory' inventory.id %}"
           class="btn btn-primary">Edit</a>
        <!-- Delete button -->
        <a href="{% url 'confirm_delete' 'inventory' inventory.id %}"
           class="btn btn-danger">Delete</a>
      {% endif %}
    </div>
  </div>
{% endblock content %}

lims/templates/labdata/detail_organism.html
{% extends "base.html" %}

{% load role_tags %}

{% block content %}
  <div class="container mt-4">
    <h1>Organism Details</h1>
    <dl class="row mt-4">
      <dt class="col-sm-2">Scientific Name</dt>
      <dd class="col-sm-10">
        {{ organism.sci_name }}
      </dd>
      <dt class="col-sm-2">Common Name</dt>
      <dd class="col-sm-10">
        {{ organism.common_name }}
      </dd>
      <!-- Add more fields as needed -->
    </dl>
    <!-- Navigation Buttons -->
    <div class="mt-3">
      <!-- Go back button -->
      <a href="{% url 'labdata_homepage' %}" class="btn btn-secondary">Back to List</a>
      {% if request.user|has_role:"PI" %}
        <!-- Edit button -->
        <a href="{% url 'update_organism' organism.id %}"
           class="btn btn-primary">Edit</a>
        <!-- Delete button -->
        <a href="{% url 'confirm_delete' 'organism' organism.id %}"
           class="btn btn-danger">Delete</a>
      {% endif %}
    </div>
  </div>
{% endblock content %}

lims/templates/labdata/detail_sample.html
{% extends "base.html" %}

{% load role_tags %}

{% block content %}
  <div class="container mt-4">
    <h1>Sample Details</h1>
    <dl class="row mt-4">
      <dt class="col-sm-2">Collect Date</dt>
      <dd class="col-sm-10">
        {{ sample.collect_date }}
      </dd>
      <dt class="col-sm-2">Type</dt>
      <dd class="col-sm-10">
        <a href="{{ sample.type.get_absolute_url }}">{{ sample.type }}</a>
      </dd>
      <dt class="col-sm-2">Specimen</dt>
      <dd class="col-sm-10">
        <a href="{{ sample.specimen.get_absolute_url }}">{{ sample.specimen }}</a>
      </dd>
      <!-- Add more fields as needed -->
    </dl>
    <!-- Navigation Buttons -->
    <div class="mt-3">
      <!-- Go back button -->
      <a href="{% url 'labdata_homepage' %}" class="btn btn-secondary">Back to List</a>
      {% if request.user|has_role:"PI" %}
        <!-- Edit button -->
        <a href="{% url 'update_sample' sample.id %}" class="btn btn-primary">Edit</a>
        <!-- Delete button -->
        <a href="{% url 'confirm_delete' 'sample' sample.id %}"
           class="btn btn-danger">Delete</a>
      {% endif %}
    </div>
  </div>
{% endblock content %}

lims/templates/labdata/detail_sample_results.html
{% extends "base.html" %}

{% load role_tags %}

{% block content %}
  <div class="container mt-4">
    <h1>Sample Result Details</h1>
    <dl class="row mt-4">
      <dt class="col-sm-2">Sample</dt>
      <dd class="col-sm-10">
        <a href="{{ sample_result.sample.get_absolute_url }}">{{ sample_result.sample }}</a>
      </dd>
      <dt class="col-sm-2">Test</dt>
      <dd class="col-sm-10">
        <a href="{{ sample_result.test.get_absolute_url }}">{{ sample_result.test }}</a>
      </dd>
      <dt class="col-sm-2">Analyst</dt>
      <dd class="col-sm-10">
        {{ sample_result.analyst }}
      </dd>
      <dt class="col-sm-2">Reagent</dt>
      <dd class="col-sm-10">
        {% for reagent in sample_result.reagents.all %}
          <a href="{{ reagent.get_absolute_url }}">{{ reagent.name }}</a>
          {% if not forloop.last %},{% endif %}
        {% empty %}
          No reagents
        {% endfor %}
      </dd>
      <dt class="col-sm-2">Date</dt>
      <dd class="col-sm-10">
        {{ sample_result.date }}
      </dd>
      <dt class="col-sm-2">Result</dt>
      <dd class="col-sm-10">
        {{ sample_result.results }}
      </dd>
    </dl>
    <!-- Navigation Buttons -->
    <div class="mt-3">
      <!-- Go back button -->
      <a href="{% url 'labdata_homepage' %}" class="btn btn-secondary">Back to List</a>
      {% if request.user|has_role:"PI" %}
        <!-- Edit button -->
        <a href="{% url 'update_sample_results' sample_result.id %}"
           class="btn btn-primary">Edit</a>
        <!-- Delete button -->
        <a href="{% url 'confirm_delete' 'sample_result' sample_result.id %}"
           class="btn btn-danger">Delete</a>
      {% endif %}
    </div>
  </div>
{% endblock content %}

lims/templates/labdata/detail_sample_type.html
{% extends "base.html" %}

{% load role_tags %}

{% block content %}
  <div class="container mt-4">
    <h1>Sample Type Details</h1>
    <dl class="row mt-4">
      <dt class="col-sm-2">Source</dt>
      <dd class="col-sm-10">
        {{ sample_type.source }}
      </dd>
      <dt class="col-sm-2">Description</dt>
      <dd class="col-sm-10">
        {{ sample_type.description }}
      </dd>
      <!-- Add more fields as needed -->
    </dl>
    <!-- Navigation Buttons -->
    <div class="mt-3">
      <!-- Go back button -->
      <a href="{% url 'labdata_homepage' %}" class="btn btn-secondary">Back to Dashboard</a>
      {% if request.user|has_role:"PI" %}
        <!-- Edit button -->
        <a href="{% url 'update_sampletype' sample_type.id %}"
           class="btn btn-primary">Edit</a>
        <!-- Delete button -->
        <a href="{% url 'confirm_delete' 'sample_type' sample_type.id %}"
           class="btn btn-danger">Delete</a>
      {% endif %}
    </div>
  </div>
{% endblock content %}

lims/templates/labdata/detail_specimen.html
{% extends "base.html" %}

{% load role_tags %}

{% block content %}
  <div class="container mt-4">
    <h1>Specimen Details</h1>
    <dl class="row mt-4">
      <dt class="col-sm-2">Specimen ID</dt>
      <dd class="col-sm-10">
        {{ specimen.specimen_id }}
      </dd>
      <dt class="col-sm-2">Organism</dt>
      <dd class="col-sm-10">
        <a href="{{ specimen.organism.get_absolute_url }}">{{ specimen.organism }}</a>
      </dd>
      <dt class="col-sm-2">First Name</dt>
      <dd class="col-sm-10">
        {{ specimen.first_name }}
      </dd>
      <dt class="col-sm-2">Last Name</dt>
      <dd class="col-sm-10">
        {{ specimen.last_name }}
      </dd>
      <dt class="col-sm-2">Date of Birth</dt>
      <dd class="col-sm-10">
        {{ specimen.dob }}
      </dd>
      <dt class="col-sm-2">Cohort</dt>
      <dd class="col-sm-10">
        {{ specimen.cohort }}
      </dd>
      <dt class="col-sm-2">Gender</dt>
      <dd class="col-sm-10">
        {{ specimen.get_gender_display }}
      </dd>
      <dt class="col-sm-2">Race</dt>
      <dd class="col-sm-10">
        {{ specimen.get_race_display }}
      </dd>
    </dl>
    <!-- Navigation Buttons -->
    <div class="mt-3">
      <!-- Go back button -->
      <a href="{% url 'labdata_homepage' %}" class="btn btn-secondary">Back to List</a>
      {% if request.user|has_role:"PI" %}
        <!-- Edit button -->
        <a href="{% url 'update_specimen' specimen.id %}"
           class="btn btn-primary">Edit</a>
        <!-- Delete button -->
        <a href="{% url 'confirm_delete' 'specimen' specimen.id %}"
           class="btn btn-danger">Delete</a>
      {% endif %}
    </div>
  </div>
{% endblock content %}

lims/templates/labdata/detail_test.html
{% extends "base.html" %}

{% load role_tags %}

{% block content %}
  <div class="container mt-4">
    <h1>Test Details</h1>
    <dl class="row mt-4">
      <dt class="col-sm-2">Name</dt>
      <dd class="col-sm-10">
        {{ test.name }}
      </dd>
      <dt class="col-sm-2">Description</dt>
      <dd class="col-sm-10">
        {{ test.description }}
      </dd>
      <dt class="col-sm-2">Reportable Results</dt>
      <dd class="col-sm-10">
        {{ test.reportable_results }}
      </dd>
    </dl>
    <!-- Navigation Buttons -->
    <div class="mt-3">
      <!-- Go back button -->
      <a href="{% url 'labdata_homepage' %}" class="btn btn-secondary">Back to List</a>
      {% if request.user|has_role:"PI" %}
        <!-- Edit button -->
        <a href="{% url 'update_test' test.id %}" class="btn btn-primary">Edit</a>
        <!-- Delete button -->
        <a href="{% url 'confirm_delete' 'test' test.id %}"
           class="btn btn-danger">Delete</a>
      {% endif %}
    </div>
  </div>
{% endblock content %}

lims/templates/labdata/form_template.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
  Form
{% endblock title %}
{% block content %}
  <h1>{{ title }}</h1>
  <form method="post" class="form-horizontal">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">{{ button_label }}</button>
      </div>
    </div>
  </form>
{% endblock content %}